# Generated by Django 2.1.3 on 2018-11-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaxTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(default=0.0)),
                ('region', models.IntegerField(choices=[(0, 'UK'), (1, 'England'), (2, 'Scotland'), (3, 'Wales')])),
                ('record_date', models.DateField()),
            ],
            options={
                'abstract': False,
                'ordering': ['record_date'],
            },
        ),
        migrations.CreateModel(
            name='MinTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(default=0.0)),
                ('region', models.IntegerField(choices=[(0, 'UK'), (1, 'England'), (2, 'Scotland'), (3, 'Wales')])),
                ('record_date', models.DateField()),
            ],
            options={
                'abstract': False,
                'ordering': ['record_date'],
            },
        ),
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(default=0.0)),
                ('region', models.IntegerField(choices=[(0, 'UK'), (1, 'England'), (2, 'Scotland'), (3, 'Wales')])),
                ('record_date', models.DateField()),
            ],
            options={
                'abstract': False,
                'ordering': ['record_date'],
            },
        ),
    ]
